version: 0.2

phases:
  pre_build:
    commands:
      - echo Build started on `date`
      - mvn install:install-file -Dfile=ojdbc7-11.2.0.jar -DgroupId=com.oracle -DartifactId=ojdbc7 -Dversion=11.2.0 -Dpackaging=jar
      - mvn clean package
  build:
    commands:
      - echo Build completed on `date`
      - mvn clean package
      - ls
      - mv target/cirrus-Back-1.0-SNAPSHOT.war cirrus-Back-1.0-SNAPSHOT.war 
      - ls
artifacts:
  files:
    - cirrus-Back-1.0-SNAPSHOT.war
    - .ebextensions/**/*
